schema-version: v2
kind: plugin
metadata:
  name: nest-entity
  display-name: nest-entity
  description: Plugin para criar uma entidade, com módulo, service e etc, dentro do nestjs
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - typescript
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - name: nestjs
      version: 7.0.0
  stk-projects-only: false
  inputs:
    - label: Name of the new entity
      name: model_name
      type: text
      required: true
      default: Client
      pattern: '^[a-z_]+$'
      help: 'Name of the entity, using snake_case, like "cliente" or "cliente_telefone". Será usado para nomear a pasta, arquivos e tabelas'
  